### ISSUE TITLE
Cannot read property 'substring' of null in PIWH while ts-node outputs perfectly.

### ISSUE THREAD

**Issue by mayanksha** [stevekane/promise-it-wont-hurt#125]
Hi everyone!
My solution is given below. When I try to use ts-node to run the program, I don't get any error and the program successfully prints REJECTED! in each of the four cases mentioned below, while the same is not the case when I do promise-it-wont-hurt verify reject.ts.

Just the first one :
 
```promise.then(undefined, onReject);```

successfully gets verified by PIWH while the last three (used one at a time)  

```
//promise.then().catch(onReject);
//promise.then(undefined).catch(onReject);
//promise.catch(onReject);
```
throw an error. I tried using tsc to compile the reject.ts files in each case and then using `node reject.js ` still it outputs REJECTED! , but such is not the case with PIWH. 

I am including both, my solution and the error message. Pardon me if I'm wrong here, but I can't seem to find any solution googling it. 

One more question : 
The official solution mentioned in PIWH states the usage of null in place of undefined as the resolve function. I know the differences between null and undefined, but which should I be preferring in this case? Is it just a style-guide thingy or does it have some intricacy behind it which I'm not able to comprehend? And which should I be preferring while writing code?

Thanks in advance! 
```
//#MY SOLUTION

var onReject = (error) => console.log(error.message);
var promise = new Promise((resolve, reject) => {
	var error = new Error('REJECTED!');
	setTimeout(() => {  return reject(error)}, 300);
});
//promise.then(undefined, onReject);
//promise.then().catch(onReject);
//promise.then(undefined).catch(onReject);
//promise.catch(onReject);
```
>#ERROR MESSAGE
>
> (node:5750) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
> /usr/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:9
>     return stack[0].getFileName().substring(0, ctx.mainProgram.length)
>                                  ^
> 
> TypeError: Cannot read property 'substring' of null
>     at isInUserCode (/usr/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:9:34)
>     at Promise.then (/usr/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:51:22)
>     at Promise.catch (<anonymous>)
>     at Object.<anonymous> (/home/codermayank/git/node/Promise/reject.ts:9:30)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
> ✗ Expected execution time: 361±100ms. Submission execution time: 54ms.
>

**Comment by TylerYang** [comment]
Same issue here, 

### Reproduce Steps
- `npm install -g promise-it-wont-hurt@latest`
- Create a file `rejected-promise.js` which contains content below
```
const promise = new Promise(function (resolve, reject) {
  setTimeout(function () {
    reject(new Error('REJECTED!'))
  }, 300)
})

function onReject (error) {
  console.log(error.message)
}

promise.then(null).catch(onReject)
```
- `promise-it-wont-hurt verify rejected-promise.js`

### Expected Behaviour
Outputing the result like `success` or `failed`.

### Actual See
```
(node:53129) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:16
    return stack[0].getFileName().substring(0, ctx.mainProgram.length)
                                 ^

TypeError: Cannot read property 'substring' of null
    at isInUserCode (/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:16:34)
    at Promise.then (/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:58:22)
    at Promise.catch (<anonymous>)
    at Object.<anonymous> (/Users/tyler/study/nodeschool/promise/program.js:11:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
```


### Reason
https://github.com/stevekane/promise-it-wont-hurt/blob/v1.1.2/exercises/reject_a_promise/wrap.js#L9
```
function isInUserCode(stack) {
    return stack[0].getFileName().substring(0, ctx.mainProgram.length)
      === ctx.mainProgram;
  }
```
Basically, the `stack` is the result return from [`ctx.$captureStack`](https://github.com/workshopper/workshopper-wrappedexec/blob/v0.1.2/exec-wrap.js#L32).  
And  `stack[0].getFileName()` would return the filename **only if this function was defined in a script returns the name of the script.** check [this link](https://github.com/v8/v8/wiki/Stack-Trace-API#customizing-stack-traces) for more details.

The thing is, while we are using node.js build in `Promise`, it's not defined in javascript file. It's a native method which was implemented in C++.  See [node/async_wrap.cc](https://github.com/nodejs/node/blob/master/src/async_wrap.cc#L233).

As a result, `stack[0].getFileName()` would return `null`, and we got the exception below. 
```
(node:5750) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:9
return stack[0].getFileName().substring(0, ctx.mainProgram.length)
^

TypeError: Cannot read property 'substring' of null
at isInUserCode (/usr/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:9:34)
at Promise.then (/usr/lib/node_modules/promise-it-wont-hurt/exercises/reject_a_promise/wrap.js:51:22)
at Promise.catch ()
at Object. (/home/codermayank/git/node/Promise/reject.ts:9:30)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
✗ Expected execution time: 361±100ms. Submission execution time: 54ms.
```
