### ISSUE TITLE
Error in excercise "throw an error"

### ISSUE THREAD

**Issue by amanmj** [stevekane/promise-it-wont-hurt#126]
The stack trace of exception that occurs will never match as the path to the file cannot be always the same.
You expect to save the file at exactly the same path .
Check the below screenshot
<img width="1434" alt="screen shot 2017-07-21 at 2 25 39 pm" src="https://user-images.githubusercontent.com/7460559/28456659-b1e997e6-6e20-11e7-9414-a1cc73d2ae50.png">

**Comment by natcreates** [comment]
Having this exact same issue.

**Comment by ijoel** [comment]
See the workaround that @loicjaouen posted to move forward.
https://github.com/stevekane/promise-it-wont-hurt/issues/102#issuecomment-331394301

**Comment by amanmj** [comment]
Awesome

**Comment by addaleax** [comment]
I think this has been fixed now, so I’m closing this. Please feel free to re-open if you run into any more trouble!

**Comment by amanmj** [comment]
Thanks!
