### ISSUE TITLE
Error in verifying exercise "An important rule"

### ISSUE THREAD

**Issue by amanmj** [stevekane/promise-it-wont-hurt#127]
The error stack trace cannot be the same as the file location can be different for different users
<img width="1427" alt="screen shot 2017-07-21 at 2 49 03 pm" src="https://user-images.githubusercontent.com/7460559/28457462-d80667d0-6e23-11e7-82cc-a9f8f27e671c.png">

**Comment by gyaresu** [comment]
To get past this you can call the actual solution file which then gives the PATH it expects to see (as part of the comparison).

In my case:
`$ promise-it-wont-hurt verify /Users/gyaresu/.node/lib/node_modules/promise-it-wont-hurt/exercises/an_important_rule/solution/solution.js`

![screen shot 2017-10-12 at 2 30 58 am](https://user-images.githubusercontent.com/29263/31489489-9e8172b2-aef5-11e7-8a19-cf09685e3cb1.png)

**Comment by addaleax** [comment]
I think this has been fixed now, so I’m closing this. Please feel free to re-open if you run into any more trouble!

**Comment by amanmj** [comment]
Sure thanks
