### ISSUE TITLE
ES6 promises compatibility

### ISSUE THREAD

**Issue by yoshuawuyts** [stevekane/promise-it-wont-hurt#14]
There's no note on es6 promise compatibility, so I was wondering how well this course teaches you that.

**Comment by bajtos** [comment]
+1

Both io.js@1.x and node@0.12 ship ES6-compatible `Promise` implementation enabled by default. When it comes to user-land promise implementation, Bluebird seems to be much more popular than q these days.

**Comment by TimothyGu** [comment]
+1. I have just successfully completed all exercises with the io.js native Promise, with the exception of `Q.fcall` and `Q.all` etc.

The tag line of this module is: "Uses the popular "Q" library as a default implementation of Promises/A+".

Thing is, Q extends far beyond A+, and deferreds, a central part of this workshopper, are more jQuery-esque than anything.

So yes, I would definitely support converting this workshop to Promise fully, and I would see what i can do during the spring break.

**Comment by bajtos** [comment]
See also #46, which is discussing a general update of the adventure.

**Comment by TimothyGu** [comment]
Let's merge this to #46.
