### ISSUE TITLE
Error in Lesson 2:Verify: You did not use promise constructor and fulfill method (though i used)

### ISSUE THREAD

**Issue by June057** [stevekane/promise-it-wont-hurt#147]
const Promise = require('es6-promise');

 return new Promise(function (fulfill, reject) {
     setTimeout(function () {
         fulfill('FULFILLED!');
     }, 300)
 })
     .then(function(val){
         console.log(val);
     });

**Comment by addaleax** [comment]
I think it’s complaining because you overwrote the “real” `Promise` constructor with `require('es6-promise')`. Does it help if you remove the first line?

**Comment by June057** [comment]
Yes Thanks.
