### ISSUE TITLE
Error starting from 2nd lesson

### ISSUE THREAD

**Issue by dbelozerovx1** [stevekane/promise-it-wont-hurt#159]
Downloaded & installed via NPM, 1st lesson worked fine, starting from 2nd one getting an error, screenshot attached, please help to solve, thanks in advance 
![image](https://user-images.githubusercontent.com/60913832/99217916-be74a980-280b-11eb-886f-a90ea604ca5f.png)

**Comment by s-maibuecher** [comment]
Quick fix: Open _[..]\node_modules\promise-it-wont-hurt\node_modules\@timothygu\workshopper-wrappedexec\wrappedexec.js_ and change `os.tmpDir` to `os.tmpdir`

See here: https://github.com/alhazmy13/serverless-offline-python/issues/18#issuecomment-666549117

**Comment by dbelozerovx1** [comment]
> Quick fix: Open _[..]\node_modules\promise-it-wont-hurt\node_modules@timothygu\workshopper-wrappedexec\wrappedexec.js_ and change `os.tmpDir` to `os.tmpdir`
> 
> See here: [alhazmy13/serverless-offline-python#18 (comment)](https://github.com/alhazmy13/serverless-offline-python/issues/18#issuecomment-666549117)

Solution actually helps me, thank you
