### ISSUE TITLE
De-deifying an important rule

### ISSUE THREAD

**Issue by eddieajau** [stevekane/promise-it-wont-hurt#17]
Would if be possible to de-deify the function name in https://github.com/stevekane/promise-it-wont-hurt/blob/master/problems/an_important_rule/problem.txt#L62. Because OMG is used commonly as a curse it can be a little off putting to those that hold it with a little more reverence. Would that be ok?

**Comment by TimothyGu** [comment]
Time out. Committed a bland fix.
