### ISSUE TITLE
First exercise does not mention resolve() 

### ISSUE THREAD

**Issue by CamiloMM** [stevekane/promise-it-wont-hurt#20]
The first exercise must be solved with the `defer.resolve` method, but this method's existance is not mentioned in the description. I was expecting it to be called that way, but I think the description should either:

1. Tell you that resolving promises is done with the `defer.resolve` method, or
2. Give you a link to the API docs.

I prefer the first one, myself.

**Comment by TimothyGu** [comment]
Revised according to ES2015 wording: https://github.com/stevekane/promise-it-wont-hurt/commit/b2881eeeafe3f686c3654ce87c62f6e469c6bc08#diff-41cba6cad45f5d5e61722a5e7f2254b4R13

Feel free to comment there.
