### ISSUE TITLE
The 5th chapter assumes the user already knows you can chain promises

### ISSUE THREAD

**Issue by CamiloMM** [stevekane/promise-it-wont-hurt#21]
The fifth chapter begins with the question:

> **Do I HAVE to return promises??**

> NO!  Fulfillment handlers may return promises OR values.

However, for a user that didn't knew about promises before, this will be hard to understand, because to this point it wasn't explained that fulfillment handlers should return anything at all. It wasn't even shown that you can chain them.

I think this style of course should target the lowest common denominator, i.e., the user that never saw promises before but wants to learn them from scratch. But maybe this was a refresher by design?

**Comment by TimothyGu** [comment]
I will add a separate lesson for this right before this one. Thanks!
