### ISSUE TITLE
Lesson 3 "Always Async" problem description incorrect?

### ISSUE THREAD

**Issue by mlilley** [stevekane/promise-it-wont-hurt#28]
From lesson 3, "Always Async": 
> "The Promises/A+ spec declares that promises MUST fire their resolution/rejection
> function on the same turn of the event loop that they are created on."

Is this a typo?  Isn't the purpose of this lesson to demonstrate that the opposite is true?

Shouldn't "MUST fire" be replaced with "MUST NOT fire" ?

**Comment by enerve** [comment]
Yeah, I just bumped into this issue as well.

**Comment by focusaurus** [comment]
Issue still not resolved in published NPM version. Would you consider adding a collaborator to this project to review and selectively merge PRs and publish a new version to npm? Otherwise maybe explicit mark the README as [UNMAINTAINED](http://jlongster.com/Starters-and-Maintainers)?

**Comment by TimothyGu** [comment]
Will publish a new version in a few minutes.
