### ISSUE TITLE
Step one is infinitely high. 

### ISSUE THREAD

**Issue by rboatright** [stevekane/promise-it-wont-hurt#37]
Step one has neither training material, nor pointers to tutorials which suggest a way to do step one. 

It says to set up var q and var defer and then says "make a promise, pass the console log to the then method of the promise and manually resolve it..."  

Really?   Look, I've been programming javascript for a long time.  I can chain asynchronous calls with the best of them.  (Really, webOS was all about async calls.) but guys, if you're introducing a new way to do something, you need, minimally, to either post answers, so we can jump over the starting gate, or pointers to tutorials to know how to formulate the calls to the q library to set up the promise and the then, and to resolve it. 

also, telling me to "resolve that promise manually with a setTimeout" doesn't let me know that I need to use a method called defer.resolve.  If there's absolutely no pointers into syntax, where is a naive user supposed to start from? 

Pedagogically, this tutorial sucks dead bunnies.

**Comment by vastus** [comment]
> Pedagogically, this tutorial sucks dead bunnies.

+1

**Comment by AlabamaMike** [comment]
This first problem has me turned off from continuing.  I agree with the OP on the difficulty of this task, espcially with the lack of pointers or breadcrumbs to help out those who get stuck.

**Comment by codeHatcher** [comment]
Wow, this is really bad. It took me a solid 20 minutes to figure this out. I am going to post the solution here so people can move forward. Looking at the actual solution is much more helpful than reading the text since it doesn't tell you how anything works.
```javascript
var q = require('q');
      var def = q.defer();

      def.promise.then(console.log);
      setTimeout(def.resolve, 300, "RESOLVED!");
```

let me know if you guys think we should just post solutions to these problems so people can actually learn from this tutorial. I am also interested in working on a fork of this that would be much more useful if anyone is interested.

**Comment by no7dw** [comment]
@codeHatcher +1, here's my a little sollution:

    var q = require('q')
    var defer = q.defer();
    defer.promise.then(console.log);
    setTimeout(defer.resolve, 300);
    defer.resolve('RESOLVED!');

but why setTimeout can be pass with three parameters instead of two parameters ?

**Comment by no7dw** [comment]
for the same reason , I print my solution of step 2 :

        var q = require('q')
        var defer = q.defer();
        var fun = function(result){
                console.log(result);
        };
        defer.promise.then(null, fun);
        setTimeout(defer.reject, 300);
        defer.reject('REJECTED!');

**Comment by tdd** [comment]
@TimothyGu WRT that problem, I was speaking with @stevekane over email recently and we figured the whole thing should be rewritten using an API closer to ES6, such as [rsvp](https://github.com/tildeio/rsvp.js/) or even [es6-promise](https://github.com/jakearchibald/es6-promise).

I'm all for it, and suggest I open a dedicated issue and work out a PR for that. What do you think?

**Comment by TimothyGu** [comment]
@tdd I think so too. I'd use es6-promise **only** as a fallback if the user is not already using a promise-capable Node.js/io.js. In case you haven't noticed, I have put up my solutions to the problems without using Q here: https://github.com/TimothyGu/promise-it-wont-hurt-promise

Also you know what would be productive is if we submit a PR for every module ported so we can review it faster, and later commits wouldn't have the same problems.

**Comment by tdd** [comment]
Hey Tim, by "every module", you mean every problem, right? That sounds like a good idea, definitely. I'm kinda underwater for the next few days, but I can def find time to review the work if you're blazing through it! From next Thursday on I'll have more time to help and wrap this up.

**Comment by TimothyGu** [comment]
Step one is now splitted into two:

1. introduction to promises and warmup with setTimeout
2. introduction to promise syntax

Feel free to read the new lessons (in `no-q` branch) and comment on b2881eeeafe3f686c3654ce87c62f6e469c6bc08.

Thank you all!

**Comment by ajfarkas** [comment]
So psyched this is fixed. Came back to this workshop and it's fantastic!
