### ISSUE TITLE
Chp 3. setTimeout not needed

### ISSUE THREAD

**Issue by enerve** [stevekane/promise-it-wont-hurt#39]
to_reject_or_not_to_reject
The description could perhaps mention that setTimeout is not required for this exercise. (Although my program was verified just fine despite using setTimeout)

**Comment by TimothyGu** [comment]
> The description could perhaps mention that setTimeout is not required for this exercise. (Although my program was verified just fine despite using setTimeout)

That's what promises are all about! (The abstraction between async and sync code)

**Comment by TimothyGu** [comment]
I'll fix this tomorrow.
