### ISSUE TITLE
Alternative way to run the workshop

### ISSUE THREAD

**Issue by oren** [stevekane/promise-it-wont-hurt#49]
for those who got docker install it can be 1 liner - `docker run -it -v $(pwd):/root oreng/promises-workshop`

It's a tiny image (28 MB) since I run io.js on Alpine Linux instead of Debian/Ubuntu.
more details here:  https://registry.hub.docker.com/u/oreng/promises-workshop

**Comment by TimothyGu** [comment]
Cool! Would you mind creating a pull request to update the README to reflect this?

**Comment by oren** [comment]
sure!

**Comment by oren** [comment]
done. i added 2 docker related files.
