### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by TimothyGu** [stevekane/promise-it-wont-hurt#50]
Right now there are multiple coding styles in use in PIWT. The latest addition from @tdd is in NPM style (which is also what I prefer), but the existing solutions are in @stevekane -style. We should migrate everything over.

**Comment by tdd** [comment]
That's a good point; I resisted doing that as long as Steve "owned" the codebase; basic respect, you know. If we do take over, making the coding style homogenous is best. Also, not quite npm style: I loathe comma-first :wink:

**Comment by TimothyGu** [comment]
Hmm… https://github.com/stevekane/promise-it-wont-hurt/blob/master/promiseitwonthurt.js#L9-L16

**Comment by stevekane** [comment]
Feel free to do literally ANYTHING you prefer here.  I don't mind at all where the commas or spaces or anything are.  In fact, I would suggest you adhere to the recently released style proposed by @feross in his module.  I think it's an acceptable standard that reflects the opinions of many top module authors.  Blaze the trails friends.

**Comment by feross** [comment]
If you like npm style, then https://npmjs.com/package/standard is for you :-)

Also, npm ditched their comma-first rule a while ago, even if their [docs](https://docs.npmjs.com/misc/coding-style#comma-first) haven't been updated yet!

**Comment by stevekane** [comment]
I also stopped it a long time ago myself.  I now use the more boring var-per-line style and have completely abandoned semicolons.

**Comment by TimothyGu** [comment]
Personally I actually like comma-first, but if you guys prefer I can work with standard. (TBH the name “standard” reminds me of common md and different colors of the bike shed…)

**Comment by stevekane** [comment]
No preference but I think it might be the least provocative to go w/ the ver-per-line style as it's most familiar and comes with the lightest overhead for newcomers.

**Comment by tdd** [comment]
Airbnb's style guide reflects the community's main sentiment, and I think we should go along that (and yes, it happens to fit my personal style).
