### ISSUE TITLE
Tests don't really test much

### ISSUE THREAD

**Issue by Sequoia** [stevekane/promise-it-wont-hurt#55]
for exercise 2:

* Create a deferred
* Create a function to print error.message using console.log.
* Pass this function as a rejection handler to the "then" method of your promise.
* Manually reject that promise
* using setTimeout with a delay of 300ms
* reject with the value "REJECTED!"

Passing solution:
```javascript
console.log('REJECTED!');
```

I know testing these async sorta things can be tricky but imo the test should check for more than "outputs 'REJECTED!'"

**Comment by Sequoia** [comment]
users may think they have solved the exercise when in fact they did it wrong.

**Comment by TimothyGu** [comment]
Yes, I'm trying to find a way to fix this.

**Comment by Sequoia** [comment]
mmm... /cc @rvagg @martinheidegger There is a way to do this with workshopper (I think) but I don't know what it is. substack/adventure is more flexible and might make this easier but would basically require a total rewrite so if you can figure out a way to do it with workshopper I recommend that!

**Comment by martinheidegger** [comment]
https://github.com/workshopper/workshopper-adventure (workshopper & adventure compatible ... mostly anyways)

**Comment by Sequoia** [comment]
@martinheidegger how does that solve the async problem? (i.e. "`assert` no output; wait 300ms; `assert` output = `'FOO!'`")

**Comment by martinheidegger** [comment]
@Sequoia It doesn't solve the problem but it should give you a tool to help solve the problem (you can fix it using an adventurous way).

**Comment by Sequoia** [comment]
ohh that lib allows you to intermix lesson types. I get you. :smile_cat: cool!

**Comment by TimothyGu** [comment]
@Sequoia care to make a prototype?

**Comment by Sequoia** [comment]
@TimothyGu nah :smile_cat: I have my own nodeschool course languishing for lack of attention :) https://github.com/Sequoia/clijs/tree/master/exercises

**Comment by stevekane** [comment]
The shitty way reporting is done in this module goes way back to the very very awkward API for the original workshopper (which was designed for streams).  This has probably changed a lot and there are likely now better solutions.

**Comment by TimothyGu** [comment]
I've started to add [considerably](https://github.com/stevekane/promise-it-wont-hurt/blob/no-q/exercises/reject_a_promise/exercise.js#L18-L22) [more](https://github.com/stevekane/promise-it-wont-hurt/blob/no-q/exercises/reject_a_promise/exercise.js#L33-L72) [tests](https://github.com/stevekane/promise-it-wont-hurt/blob/no-q/exercises/reject_a_promise/wrap.js). I haven't finished rewriting everything yet, but this is well on my plan of moving forward.
