### ISSUE TITLE
"Do some work" has an inaccurate spec

### ISSUE THREAD

**Issue by PeterBorah** [stevekane/promise-it-wont-hurt#6]
The problem for Do Some Work says:

> A JSON payload will be returned to you containing a primary key called "id". 

However, a simple string is returned (as `text/plain`) instead. Either the problem statement or the actual problem should be changed, depending on what is intended.

**Comment by talexand** [comment]
Was this resolved on the npm side? I still have instructions and tests that match OP's issue.

**Comment by amidart** [comment]
I'm having this issue too (installed from npm)
