### ISSUE TITLE
Cannot install this workshop

### ISSUE THREAD

**Issue by itsyogesh** [stevekane/promise-it-wont-hurt#64]
Hi there, I was trying to install this workshop but wasn't able to because apparently `timothygu/workshopper` is not in the npm registry. I am pasting the whole error log, just in case.

```
npm install -g promise-it-wont-hurt@latest
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'timothygu/workshopper' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'promise-it-wont-hurt'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 15.2.0
npm ERR! command "/Users/Yogesh/.nvm/v0.10.33/bin/node" "/Users/Yogesh/.nvm/v0.10.33/bin/npm" "install" "-g" "promise-it-wont-hurt@latest"
npm ERR! cwd /Users/Yogesh/Projects/Playground/promise-shop
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```

**Comment by TimothyGu** [comment]
> ```
> npm ERR! npm -v 1.4.28
> ```

I am using a specific kind of packages called "scoped packages" which are my forks of the official packages. Unfortunately your npm version doesn't seem to support them :(

I will convert these packages to regular packages and you can give a try then.

**Comment by itsyogesh** [comment]
Great, thanks. So in the meantime, is there a way in which I can fork this and then change the package.json file to use `workshopper/workshopper` package instead. I haven't use npm that extensively, but I am guessing I can install modules from local repos as well.

**Comment by TimothyGu** [comment]
Indeed when I am trying to install promise-it-wont-hurt on Node.js 0.10 this shows up:

```
$ npm i promise-it-wont-hurt
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm ERR! Error: This version of npm doesn't support scoped packages (caused by reference to @timothygu/workshopper@^2.7.2). Update to npm@2+.
npm ERR!     at add (/home/timothy_gu/.nvm/v0.10.41/lib/node_modules/npm/lib/cache.js:248:15)
npm ERR!     at Function.cache.add (/home/timothy_gu/.nvm/v0.10.41/lib/node_modules/npm/lib/cache.js:208:10)
npm ERR!     at resolver (/home/timothy_gu/.nvm/v0.10.41/lib/node_modules/npm/lib/install.js:712:11)
npm ERR!     at null._onTimeout (/home/timothy_gu/.nvm/v0.10.41/lib/node_modules/npm/lib/install.js:666:7)
npm ERR!     at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-74-generic
npm ERR! command "/home/timothy_gu/.nvm/v0.10.41/bin/node" "/home/timothy_gu/.nvm/v0.10.41/bin/npm" "i" "promise-it-wont-hurt"
npm ERR! cwd /home/timothy_gu/workshopper/test
npm ERR! node -v v0.10.41
npm ERR! npm -v 1.4.29
npm ERR! not ok code 0
```

> So in the meantime, is there a way in which I can fork this and then change the package.json file to use `workshopper/workshopper` package instead.

Not to my best knowledge.

Please re-test installing now. I switched back to the official, unforked workshopper module for now, but beware that it contains some bugs. Don't press `q` in the terminal in the menu (if you do you'll see the bug).

**Comment by TimothyGu** [comment]
And, if possible, please upgrade to the newest version of Node.js and npm to enjoy the newest features ;)

**Comment by itsyogesh** [comment]
I am using nvm, I should probably switch to a different node version. What version do recommend ? I can upgrade to 4.0+ if this workshop contains any es6 features.

**Comment by TimothyGu** [comment]
No it does not, but I'd recommend at least 4 (I personally use 5), just because it's newer. 0.10.0 was released almost three years ago!

This workshop uses no ES2015 features. We are in the process of rewriting it to use ES2015 promises with a polyfill, but even then you don't need any ES2015-capable runtimes.

**Comment by itsyogesh** [comment]
So I installed v5.3 and installed the workshop again. The installation was completed, but when I type `promise-it-wont-hurt`, it throws an error saying it cannot find a module `'@timothygu/workshopper'`. I am attaching the entire error log.

```
promise-it-wont-hurt
module.js:328
    throw err;
    ^

Error: Cannot find module '@timothygu/workshopper'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Yogesh/.nvm/versions/node/v5.3.0/lib/node_modules/promise-it-wont-hurt/promiseitwonthurt.js:3:21)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by TimothyGu** [comment]
Ugh… forgot to change the `require` line after changing deps… sorry about that. Should REALLY be fixed now.

**Comment by TimothyGu** [comment]
Also, the latest Node.js is 5.5.0 now ;) You can simply do `nvm install 5`: it will install the latest 5.* version.

**Comment by itsyogesh** [comment]
Great, its working now. I guess we should update the documentation for the node & npm version. 

Saw that node update in the node-weekly this week. I don't know why, but I felt upgrading to v5.5.0 was too bleeding edge tech for me. :P
