### ISSUE TITLE
Error running boilerplate code for Exercise 2

### ISSUE THREAD

**Issue by wheelerlaw** [stevekane/promise-it-wont-hurt#68]
Originally I had this as a solution:

```javascript
'use strict'
require('es6-promise');

var promise = new Promise(function(fulfill, reject){
        setTimeout(fulfill('FULFILLED!'), 300);
});

promise.then(console.log);
```

But I kept getting the following error:
```
/home/wheeler/learning/promise-it-wont-hurt/node_modules/es6-promise/dist/es6-promise.js:943
      if (P && Object.prototype.toString.call(P.resolve()) === '[object Promise]' && !P.cast) {
                                                ^

TypeError: P.resolve is not a function
    at lib$es6$promise$polyfill$$polyfill (/home/wheeler/learning/promise-it-wont-hurt/node_modules/es6-promise/dist/es6-promise.js:943:49)
    at Object.<anonymous> (/home/wheeler/learning/promise-it-wont-hurt/node_modules/es6-promise/dist/es6-promise.js:965:5)
    at Object.<anonymous> (/home/wheeler/learning/promise-it-wont-hurt/node_modules/es6-promise/dist/es6-promise.js:966:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/wheeler/learning/promise-it-wont-hurt/2.js:2:1)
✗ Expected execution time: 352±100ms. Submission execution time: 49ms.
```

But then I tried running the boilerplate code, with the addition of the `require` at the top, and kept running into the same issue.

**Comment by TylerMoeller** [comment]
I just went through this exercise for the first time - others can correct me if I'm overlooking a detail (or five). In Node.js `setTimeout` uses the syntax: 

```javascript
setTimeout(callback, delay[, arg][, ...])`
```

So, you'll need to change this line to use a callback as the first argument:

```javascript
setTimeout(fulfill('FULFILLED!'), 300);
```

You can do this with an anonymous function, like:

```javascript
setTimeout(function() {
  fulfill('FULFILLED!');
  }, 300
);
```

**Comment by TimothyGu** [comment]
Yeah we changed it so that you shouldn't `require('es6-promise')` yourself.

**Comment by bambery** [comment]
Can the text for the exercise please be updated? As of right now, it still seems to indicate that you should be adding that line, since right above the boilerplate it says:

Then, in the main file in your app, add the following line:

    require('es6-promise')

Do I still need to npm install it, and the requring is handled by the checking script? Or did I not need to explicitly install it? I can submit a pr to change the text if I understand what it should say.

**Comment by TimothyGu** [comment]
I think you might have misread the section.

https://github.com/stevekane/promise-it-wont-hurt/blob/bfa0425790ca4a4d36f080787f9f524426e64850/exercises/fulfill_a_promise/problem.md#setup:

> However, if you are stuck with an older version of Node.js, don’t fret: for this workshopper, a promise implementation will be **automatically supplied** if none is available.
>
> When writing your own code, we recommend using es6-promise polyfill, since it aims to be strictly compliant to ES2015 without any extra features …

(bold type in original text)
