### ISSUE TITLE
values and promises requires specific syntax

### ISSUE THREAD

**Issue by ajfarkas** [stevekane/promise-it-wont-hurt#69]
My solution to values and promises uses the syntax:
````js
var attachTitle = function(name) { return 'DR. '+name }
````
and gets rejected. When I change the syntax to
````js
function attachTitle(name) { return 'DR. '+name }
````
my code passes. 

I'll take a look at the code and make a PR, but wanted to get this in as an issue.

**Comment by TimothyGu** [comment]
This is somewhat intentional: https://github.com/stevekane/promise-it-wont-hurt/blob/master/exercises/values_and_promises/wrap.js#L26
