### ISSUE TITLE
Getting 404 while installing through npm

### ISSUE THREAD

**Issue by siddharthkore** [stevekane/promise-it-wont-hurt#71]
The command "npm install -g promise-it-wont-hurt@latest" mentioned in the "Install & Update" section gives error:
/promise-shop$ npm install -g promise-it-wont-hurt@latest
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'timothygu/workshopper-wrappedexec' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'promise-it-wont-hurt'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.2.0-30-generic
npm ERR! command "/home/siddharth_ubuntu/.nvm/v0.10.36/bin/node" "/home/siddharth_ubuntu/.nvm/v0.10.36/bin/npm" "install" "-g" "promise-it-wont-hurt@latest"
npm ERR! cwd /home/siddharth_ubuntu/Nodejs_WorkSpace/nodeschool_promises/promise-shop
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

**Comment by siddharthkore** [comment]
What could be wrong over here

**Comment by stanzheng** [comment]
try updating your version of node and npm and try again? it looks like you're on node .10 and npm 1.4

it works fine with node 4 and npm 3.

**Comment by siddharthkore** [comment]
yes. Thats the problem. I have node version .10 installed in my machine since it was giving issues in my project. However, updating to 0.12.4 and with npm version 2.10.1, I was able to install promise-it-wont-hurt module.
Thanks.
