### ISSUE TITLE
Exercise 9 - Promise is not defined Error

### ISSUE THREAD

**Issue by jwred5** [stevekane/promise-it-wont-hurt#72]
For some reason, on exercise 9, the environment cannot find Promise.

I tested this by using "promise-it-wont-hurt run ~script for exercise 2 which passed~" while under exercise 2, and then using the same command under exercise 9.

Under exercise 2, the script was run as expected and output "FULFILLED!" as expected.

Under exercise 9, the script threw "ReferenceError: Promise is not defined"

I expect this hasn't been noticed by many people since the verification step will pass anytime there is blank output to stdout, which is always the case when an error is thrown.

Attached is a copy of the script I wrote for exercise 2.

[2-fulfill.txt](https://github.com/stevekane/promise-it-wont-hurt/files/177119/2-fulfill.txt)

**Comment by keithk** [comment]
@jwred5 I just ran through this and got that error when not putting 'new' before calling Promise. Can you post your working code?

**Comment by gjbianco** [comment]
I noticed this error on exercise 9 and I also get it on exercise 10, even when using Promise.resolve().

```javascript
// ...
Promise.resolve(1)
  .then(iterate)
  // ...
  .then(alwaysThrows)
  // ...
  .catch(console.log);

**Comment by TimothyGu** [comment]
I'll take a look later today.

**Comment by gasp** [comment]
At Nodeschool Paris today, we reproduced using nvm and versions 4 and 6.
With node v4.x it works perfectly and `console.log(error)` outputs something like `"[SyntaxError: Unexpected token o]"`
With node v6.2.0 `console.log(error)` outputs something like `"SyntaxError: Unexpected token o in JSON at position 1\n     at Object.parse (native)\n    at /home/gasp/nodeschool/promise_throw.js:7:17"\n (blah blah blah)`

Trouble is: `/home/gasp/nodeschool/promise_throw.js` is unique to my working file, the solution is stored into `/usr/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:6:20` and this won't match.

**Comment by addaleax** [comment]
I think this is all resolved now. Let us know if you run into any more trouble!
