### ISSUE TITLE
Can't install this module

### ISSUE THREAD

**Issue by YueyangZhang** [stevekane/promise-it-wont-hurt#74]
C:\SelfLearning\promise-shop>npm install -g promise-it-wont-hurt
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\4.x\\node.exe" "C:\\Program Files\\nodejs\\4.x\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "-g" "promise-it-wont-hurt"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code E500

npm ERR! internal server error : @timothygu/workshopper
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\SelfLearning\promise-shop\npm-debug.log

Above is the error I got. Could somebody help me on this?

**Comment by TimothyGu** [comment]
You need to update your npm.
