### ISSUE TITLE
exercise 06 - what is running supposed to do?

### ISSUE THREAD

**Issue by bambery** [stevekane/promise-it-wont-hurt#77]
I'm confused as to what output I am supposed to see when just running program06. 

I have written some code that should output to console, but when I run, I get no output at all. Previous questions would throw errors or show syntax problems, but when I just enter garbage and run it, I get nothing. I'm not sure if I should see anything at all? I realize this question is supposed to be somewhat free form, but I can't determine if I have an errors.

**Comment by carloscarvallo** [comment]
It's shorcuts exercise? that problem don't have a specific task... what is your code?

**Comment by bambery** [comment]
Well, when I input code that threw errors in other lessons, it did not throw errors when running in exercise 6. But I am closing this, I solved it last night, even without errors! :smile:
