### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by evan-mcclaugherty** [stevekane/promise-it-wont-hurt#81]
It appears i have the correct solution to "throw an error" and "an important rule", however, the actual vs. expected is failing simply because the paths are not the same to the error.  Actual error is coming from /User/ and expected error is coming from /usr/local/.  so its failing only because the paths aren't identical.

**Comment by dannyfritz** [comment]
This appears to be an issue with installing Node through `brew` as opposed to from the Node website.

<img width="1354" alt="screen shot 2016-06-06 at 08 37 40" src="https://cloud.githubusercontent.com/assets/315788/15825812/6bc49ece-2bc2-11e6-8c2a-6d2f541d0fdd.png">

**Comment by batjko** [comment]
I'm having the same issue on Windows. 
It would be better just to compare the `error.message` values, not the full stack.

**Comment by randyxli** [comment]
I'm also encountering this problem, even after copy-pasting the solution. I second @batjko's suggestion.

>                  ACTUAL                                 EXPECTED                
> ────────────────────────────────────────────────────────────────────────────────
> 
>    "SyntaxError: Unexpected token o in JSON at position 1" ==    "SyntaxError: Unexpected token o in JSON at position 1"
>    "    at Object.parse (native)"      ==    "    at Object.parse (native)"     
>    "    at /home/rxl/src/promise-it-wont-hurt/error.js:6:20" !=    "    at /usr/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:6:20"
>    "    at parsePromised (/home/rxl/src/promise-it-wont-hurt/error.js:4:10)" !=    "    at parsePromised (/usr/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:4:10)"
>    "    at Object.<anonymous> (/home/rxl/src/promise-it-wont-hurt/error.js:13:1)" !=    "    at Object.<anonymous> (/usr/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:13:1)"
>    "    at Module._compile (module.js:541:32)" ==    "    at Module._compile (module.js:541:32)"
>    "    at Object.Module._extensions..js (module.js:550:10)" ==    "    at Object.Module._extensions..js (module.js:550:10)"
>    "    at Module.load (module.js:458:32)" ==    "    at Module.load (module.js:458:32)"
>    "    at tryModuleLoad (module.js:417:12)" ==    "    at tryModuleLoad (module.js:417:12)"
>    "    at Function.Module._load (module.js:409:3)" ==    "    at Function.Module._load (module.js:409:3)"
>    "    at Module.runMain (module.js:575:10)" ==    "    at Module.runMain (module.js:575:10)"
>    ""                                  ==    ""                                 
> 
> ────────────────────────────────────────────────────────────────────────────────

**Comment by nicoleneo** [comment]
I'm getting this error too. Obviously the file path for our solutions and the exercise solutions aren't identical as they're different files.

Should just check the first two lines of console.log: "SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
"

**Comment by TimothyGu** [comment]
@nicoleneo, just curious, what is your Node.js version?

**Comment by TimothyGu** [comment]
Yeah, only checking the first few lines would be ideal. Unfortunately, fixing the issue is more complicated as Workshopper (the module that lets us make this ... workshop) is pretty inflexible with command output stuff. I'll see what I can do in the next few days.

**Comment by batjko** [comment]
Perhaps the task could be changed to try/catch the issue and only console.log the error.message?

**Comment by nicoleneo** [comment]
@TimothyGu I use the [official Node Docker container](https://hub.docker.com/_/node/) version 6.2.2. 


```

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "SyntaxError: Unexpected token o in JSON at position 1" ==    "SyntaxError: Unexpected token o in JSON at position 1"
   "    at Object.parse (native)"      ==    "    at Object.parse (native)"     
   "    at err (/root/nodeschool_exercises/promise-it-wont-hurt/q9.js:9:35)" !=    "    at /root/.node/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:6:20"
   "    at parsePromised (/root/nodeschool_exercises/promise-it-wont-hurt/q9.js:7:19)" !=    "    at parsePromised (/root/.node/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:4:10)"
   "    at Object.<anonymous> (/root/nodeschool_exercises/promise-it-wont-hurt/q9.js:20:1)" !=    "    at Object.<anonymous> (/root/.node/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:13:1)"
   "    at Module._compile (module.js:541:32)" ==    "    at Module._compile (module.js:541:32)"
   "    at Object.Module._extensions..js (module.js:550:10)" ==    "    at Object.Module._extensions..js (module.js:550:10)"
   "    at Module.load (module.js:458:32)" ==    "    at Module.load (module.js:458:32)"
   "    at tryModuleLoad (module.js:417:12)" ==    "    at tryModuleLoad (module.js:417:12)"
   "    at Function.Module._load (module.js:409:3)" ==    "    at Function.Module._load (module.js:409:3)"
   "    at Module.runMain (module.js:575:10)" ==    "    at Module.runMain (module.js:575:10)"
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!
```

It could be possible to override [comparestdout](https://github.com/workshopper/workshopper-exercise/blob/master/comparestdout.js) line 109
```node
  outputStream = through2.obj(transform.bind(this), flush.bind(this))

  tuple(this.submissionStdout.pipe(split().slice(0, 3)), this.solutionStdout.pipe(split().slice(0, 3)))
    .pipe(outputStream)
    .pipe(process.stdout)
}

module.exports = comparestdout
```
