### ISSUE TITLE
Exercise 11 of 13: Alternate solution

### ISSUE THREAD

**Issue by domfarolino** [stevekane/promise-it-wont-hurt#90]
@stevekane 
> You probably want to use the good old Promise constructor. If you do find some other way, please [file an issue](https://github.com/stevekane/promise-it-wont-hurt/issues); I’m interested in such a solution!

Not a crazy creative solution here, and definitely not a scalable one but, ehh, here it is:

```js
function all(promise1, promise2) {
  var values = [];
  
  return promise1.then(function(promise1Val) {
    values.push(promise1Val);
    
    return promise2.then(function(promise2Val) {
      values.push(promise2Val);
      return Promise.resolve(values);
    });
  
  });
}

all(getPromise1(), getPromise2()).then(console.log);
```

**Comment by domfarolino** [comment]
In hindsight, it doesn't fetch `promise1` and `promise2` in parallel (which was probably the point lol) so I'd say it doesn't count...

**Comment by TimothyGu** [comment]
Yep. 😄
