### ISSUE TITLE
docker not found

### ISSUE THREAD

**Issue by titay2** [stevekane/promise-it-wont-hurt#91]
I was trying to install the environment on my computer but when i am trying to run the promise-it-wont-hurt-command I am getting this error

zsh: command not found: docker

**Comment by hbaqai** [comment]
You need to install [Docker](https://www.docker.com/)

**Comment by TimothyGu** [comment]
You don't need to use Docker to install promise-it-wont-hurt. Simply using the [npm method](https://github.com/stevekane/promise-it-wont-hurt#1-npm) should work.
