### ISSUE TITLE
Problem with JSON input of Excercise 9: Throw an error

### ISSUE THREAD

**Issue by divyadeepsawhney** [stevekane/promise-it-wont-hurt#94]
![screenshot 2016-08-17 19 35 17](https://cloud.githubusercontent.com/assets/7996381/17739154/c96d184e-64b1-11e6-8679-742033bf27c9.png)

The problem is with verification. I know I did it right. But, it should be resolved in this repository for future.

Thanks

**Comment by arun1595** [comment]
What if we ask the learners to just log `error.message`? This would solve the issue of comparing the string representation of the `Error` object.  ie. We only compare the following string

```
"SyntaxError: Unexpected token o in JSON at position 1"
````

I would love to add this fix to the codebase. Can someone point me on how to go about it?

**Comment by addaleax** [comment]
I think this has been fixed now, so I’m closing this. Please feel free to re-open if you run into any more trouble!
